#!/usr/bin/python

# This script requires:
#   wal

import sys
import os 

CURRENT_WALLPAPER = ' ~/.scripts/current.jpg'

try:
    os.system('feh --bg-scale ' + sys.argv[1])
    os.system('wal -i ' + sys.argv[1])
    
    os.system('cp '+ sys.argv[1] + CURRENT_WALLPAPER)

    os.system('i3-msg restart')
    os.system('~/.scripts/dunst_colors.sh')

except:

    print('Using current wallapaper....')

    os.system('feh --bg-scale ' + CURRENT_WALLPAPER)
    os.system('wal -i ' + CURRENT_WALLPAPER)
    
    os.system('i3-msg restart')
    os.system('~/.scripts/dunst_colors.sh')
    

