#!/bin/sh
lock() {
    sh ~/.scripts/lock.sh
}

prelock() {
	sh ~/.scripts/prelock.sh
}

case "$1" in
    lock)
		prelock && lock
        ;;
    logout)
		i3-msg exit 
        ;;
    suspend)
		prelock && systemctl suspend && lock
		;;
    hibernate)
		prelock && systemctl hibernate && lock
        ;;
    reboot)
        systemctl reboot
        ;;
    shutdown)
        systemctl poweroff
        ;;
    *)
        echo "Usage: $0 {lock|logout|suspend|hibernate|reboot|shutdown}"
        exit 2
esac

exit 0
