#!/usr/bin/python

import sys
import os 

CURRENT_WALLPAPER = ' ~/.scripts/currentWallpaper.jpg'

try: 
    if sys.argv[1]:
        os.system('feh --bg-scale ' + sys.argv[1])
        os.system('cp ' + sys.argv[1] + CURRENT_WALLPAPER)
except IndexError:
    os.system('feh --bg-scale '+ CURRENT_WALLPAPER)

